### ISSUE TITLE
Replace styfle/cancel-workflow-action

### ISSUE THREAD

**Issue by dopplershift** [ProjectPythia/pythia-foundations#325]
We should be able to do with with built in concurrency settings in GitHub Actions:

```yaml
concurrency:
  group: ${{ github.workflow}}-${{ github.head_ref }}
  cancel-in-progress: true
```

Would eliminate some complexity and an external dependency.
